### ISSUE TITLE
comapplequicktimesoftware

### ISSUE THREAD

**Issue by letsgo008** [xbgmsharp/piwigo-videojs#73] opened 2015-12-14 08:03 UTC
Notice: Undefined index: model in /home/www/piwigo/plugins/piwigo-videojs/include/mediainfo.php on line 116

**Comment by xbgmsharp** [comment] 2015-12-14 11:06
I would need more details. 
There is nothing on line 116, https://github.com/xbgmsharp/piwigo-videojs/blob/master/include/mediainfo.php#L116
Which version of MediaInfo are you using? 
Would you be copy paste the XML output and/or it by email. 
```
Mediainfo --Full --Output=XML --Language=raw $filename
```

**Comment by letsgo008** [comment] 2015-12-15 00:58
<?xml version="1.0" encoding="UTF-8"?>
<Mediainfo version="0.7.74">
<File>
<track type="General">
<Count>313</Count>
<StreamCount>1</StreamCount>
<StreamKind>General</StreamKind>
<StreamKind_String>General</StreamKind_String>
<StreamKindID>0</StreamKindID>
<VideoCount>1</VideoCount>
<AudioCount>1</AudioCount>
<OtherCount>2</OtherCount>
<Video_Format_List>AVC</Video_Format_List>
<Video_Format_WithHint_List>AVC</Video_Format_WithHint_List>
<Video_Codec_List>AVC</Video_Codec_List>
<Audio_Format_List>AAC</Audio_Format_List>
<Audio_Format_WithHint_List>AAC</Audio_Format_WithHint_List>
<Audio_Codec_List>AAC LC</Audio_Codec_List>
<CompleteName>Video-2015-12-13-10-58-01.mp4</CompleteName>
<FileName>Video-2015-12-13-10-58-01</FileName>
<FileExtension>mp4</FileExtension>
<Format>MPEG-4</Format>
<Format_String>MPEG-4</Format_String>
<Format_Extensions>mp4 m4v m4a m4b m4p 3gpp 3gp 3gpp2 3g2 k3g jpm jpx mqv ismv isma f4v</Format_Extensions>
<Format_Commercial>MPEG-4</Format_Commercial>
<Format_Profile>QuickTime</Format_Profile>
<InternetMediaType>video/mp4</InternetMediaType>
<CodecID>qt  </CodecID>
<CodecID_Url>http://www.apple.com/quicktime/download/standalone.html</CodecID_Url>
<Codec>MPEG-4</Codec>
<Codec_String>MPEG-4</Codec_String>
<Codec_Extensions>mp4 m4v m4a m4b m4p 3gpp 3gp 3gpp2 3g2 k3g jpm jpx mqv ismv isma f4v</Codec_Extensions>
<FileSize>18328928</FileSize>
<FileSize_String>17.5 MiB</FileSize_String>
<FileSize_String1>17 MiB</FileSize_String1>
<FileSize_String2>17 MiB</FileSize_String2>
<FileSize_String3>17.5 MiB</FileSize_String3>
<FileSize_String4>17.48 MiB</FileSize_String4>
<Duration>13642</Duration>
<Duration_String>13s 642ms</Duration_String>
<Duration_String1>13s 642ms</Duration_String1>
<Duration_String2>13s 642ms</Duration_String2>
<Duration_String3>00:00:13.642</Duration_String3>
<Duration_String4>00:00:13;19</Duration_String4>
<Duration_String5>00:00:13.642 (00:00:13;19)</Duration_String5>
<OverallBitRate_Mode>VBR</OverallBitRate_Mode>
<OverallBitRate_Mode_String>VBR</OverallBitRate_Mode_String>
<OverallBitRate>10748528</OverallBitRate>
<OverallBitRate_String>10.7 Mbps</OverallBitRate_String>
<FrameRate>29.970</FrameRate>
<FrameRate_String>29.970 fps3</FrameRate_String>
<FrameCount>409</FrameCount>
<StreamSize>33875</StreamSize>
<StreamSize_String>33.1 KiB (0%)</StreamSize_String>
<StreamSize_String1>33 KiB</StreamSize_String1>
<StreamSize_String2>33 KiB</StreamSize_String2>
<StreamSize_String3>33.1 KiB</StreamSize_String3>
<StreamSize_String4>33.08 KiB</StreamSize_String4>
<StreamSize_String5>33.1 KiB (0%)</StreamSize_String5>
<StreamSize_Proportion>0.00185</StreamSize_Proportion>
<HeaderSize>28</HeaderSize>
<DataSize>18319481</DataSize>
<FooterSize>9419</FooterSize>
<IsStreamable>No</IsStreamable>
<Encoded_Date>UTC 2015-12-13 02:58:01</Encoded_Date>
<Tagged_Date>UTC 2015-12-13 02:58:15</Tagged_Date>
<File_Modified_Date>UTC 2015-12-14 08:28:51</File_Modified_Date>
<File_Modified_Date_Local>2015-12-14 16:28:51</File_Modified_Date_Local>
<Encoded_Library>Apple QuickTime</Encoded_Library>
<Encoded_Library_String>Apple QuickTime</Encoded_Library_String>
<Encoded_Library_Name>Apple QuickTime</Encoded_Library_Name>
<comapplequicktimelocationISO6709>+31.2332+121.5340+012.571/</comapplequicktimelocationISO6709>
<comapplequicktimemake>Apple</comapplequicktimemake>
<comapplequicktimemodel>iPhone 6</comapplequicktimemodel>
<comapplequicktimesoftware>9.2</comapplequicktimesoftware>
<comapplequicktimecreationdate>2015-12-13T10:58:01+0800</comapplequicktimecreationdate>
</track>

<track type="Video">
<Count>311</Count>
<StreamCount>1</StreamCount>
<StreamKind>Video</StreamKind>
<StreamKind_String>Video</StreamKind_String>
<StreamKindID>0</StreamKindID>
<StreamOrder>0</StreamOrder>
<ID>1</ID>
<ID_String>1</ID_String>
<Format>AVC</Format>
<Format_Info>Advanced Video Codec</Format_Info>
<Format_Url>http://developers.videolan.org/x264.html</Format_Url>
<Format_Commercial>AVC</Format_Commercial>
<Format_Profile>Baseline@L3.1</Format_Profile>
<Format_Settings>1 Ref Frames</Format_Settings>
<Format_Settings_CABAC>No</Format_Settings_CABAC>
<Format_Settings_CABAC_String>No</Format_Settings_CABAC_String>
<Format_Settings_RefFrames>1</Format_Settings_RefFrames>
<Format_Settings_RefFrames_String>1 frame1</Format_Settings_RefFrames_String>
<Format_Settings_GOP>M=1, N=30</Format_Settings_GOP>
<InternetMediaType>video/H264</InternetMediaType>
<CodecID>avc1</CodecID>
<CodecID_Info>Advanced Video Coding</CodecID_Info>
<CodecID_Url>http://www.apple.com/quicktime/download/standalone.html</CodecID_Url>
<Codec>AVC</Codec>
<Codec_String>AVC</Codec_String>
<Codec_Family>AVC</Codec_Family>
<Codec_Info>Advanced Video Codec</Codec_Info>
<Codec_Url>http://developers.videolan.org/x264.html</Codec_Url>
<Codec_CC>avc1</Codec_CC>
<Codec_Profile>Baseline@L3.1</Codec_Profile>
<Codec_Settings>1 Ref Frames</Codec_Settings>
<Codec_Settings_CABAC>No</Codec_Settings_CABAC>
<Codec_Settings_RefFrames>1</Codec_Settings_RefFrames>
<Duration>13642</Duration>
<Duration_String>13s 642ms</Duration_String>
<Duration_String1>13s 642ms</Duration_String1>
<Duration_String2>13s 642ms</Duration_String2>
<Duration_String3>00:00:13.642</Duration_String3>
<Duration_String4>00:00:13;19</Duration_String4>
<Duration_String5>00:00:13.642 (00:00:13;19)</Duration_String5>
<BitRate>10641657</BitRate>
<BitRate_String>10.6 Mbps</BitRate_String>
<Width>1280</Width>
<Width_String>1280 pixel3</Width_String>
<Height>720</Height>
<Height_String>720 pixel3</Height_String>
<PixelAspectRatio>1.000</PixelAspectRatio>
<DisplayAspectRatio>1.778</DisplayAspectRatio>
<DisplayAspectRatio_String>16:9</DisplayAspectRatio_String>
<Rotation>180.000</Rotation>
<Rotation_String>180°</Rotation_String>
<FrameRate_Mode>VFR</FrameRate_Mode>
<FrameRate_Mode_String>VFR</FrameRate_Mode_String>
<FrameRate>29.970</FrameRate>
<FrameRate_String>29.970 fps3</FrameRate_String>
<FrameRate_Minimum>28.571</FrameRate_Minimum>
<FrameRate_Minimum_String>28.571 fps3</FrameRate_Minimum_String>
<FrameRate_Maximum>30.000</FrameRate_Maximum>
<FrameRate_Maximum_String>30.000 fps3</FrameRate_Maximum_String>
<FrameCount>409</FrameCount>
<Resolution>8</Resolution>
<Resolution_String>8 bit3</Resolution_String>
<Colorimetry>4:2:0</Colorimetry>
<ColorSpace>YUV</ColorSpace>
<ChromaSubsampling>4:2:0</ChromaSubsampling>
<BitDepth>8</BitDepth>
<BitDepth_String>8 bit3</BitDepth_String>
<ScanType>Progressive</ScanType>
<ScanType_String>Progressive</ScanType_String>
<Interlacement>PPF</Interlacement>
<Interlacement_String>Interlaced_PPF</Interlacement_String>
<Bits_Pixel_Frame_>0.385</Bits_Pixel_Frame_>
<StreamSize>18153311</StreamSize>
<StreamSize_String>17.3 MiB (99%)</StreamSize_String>
<StreamSize_String1>17 MiB</StreamSize_String1>
<StreamSize_String2>17 MiB</StreamSize_String2>
<StreamSize_String3>17.3 MiB</StreamSize_String3>
<StreamSize_String4>17.31 MiB</StreamSize_String4>
<StreamSize_String5>17.3 MiB (99%)</StreamSize_String5>
<StreamSize_Proportion>0.99042</StreamSize_Proportion>
<Title>Core Media Video</Title>
<Encoded_Date>UTC 2015-12-13 02:58:01</Encoded_Date>
<Tagged_Date>UTC 2015-12-13 02:58:15</Tagged_Date>
<colour_range>Limited</colour_range>
<colour_description_present>Yes</colour_description_present>
<colour_primaries>BT.709</colour_primaries>
<transfer_characteristics>BT.709</transfer_characteristics>
<matrix_coefficients>BT.709</matrix_coefficients>
</track>

<track type="Audio">
<Count>254</Count>
<StreamCount>1</StreamCount>
<StreamKind>Audio</StreamKind>
<StreamKind_String>Audio</StreamKind_String>
<StreamKindID>0</StreamKindID>
<StreamOrder>1</StreamOrder>
<ID>2</ID>
<ID_String>2</ID_String>
<Format>AAC</Format>
<Format_Info>Advanced Audio Codec</Format_Info>
<Format_Commercial>AAC</Format_Commercial>
<Format_Profile>LC</Format_Profile>
<CodecID>40</CodecID>
<Codec>AAC LC</Codec>
<Codec_String>AAC LC</Codec_String>
<Codec_Family>AAC</Codec_Family>
<Codec_CC>40</Codec_CC>
<Duration>13640</Duration>
<Duration_String>13s 640ms</Duration_String>
<Duration_String1>13s 640ms</Duration_String1>
<Duration_String2>13s 640ms</Duration_String2>
<Duration_String3>00:00:13.640</Duration_String3>
<Duration_String5>00:00:13.640</Duration_String5>
<Source_Duration>13700</Source_Duration>
<Source_Duration_String>13s 700ms</Source_Duration_String>
<Source_Duration_String1>13s 700ms</Source_Duration_String1>
<Source_Duration_String2>13s 700ms</Source_Duration_String2>
<Source_Duration_String3>00:00:13.700</Source_Duration_String3>
<BitRate_Mode>VBR</BitRate_Mode>
<BitRate_Mode_String>VBR</BitRate_Mode_String>
<BitRate>83133</BitRate>
<BitRate_String>83.1 Kbps</BitRate_String>
<Channel_s_>1</Channel_s_>
<Channel_s__String>1 channel1</Channel_s__String>
<ChannelPositions>Front: C</ChannelPositions>
<ChannelPositions_String2>1/0/0</ChannelPositions_String2>
<ChannelLayout>C</ChannelLayout>
<SamplingRate>44100</SamplingRate>
<SamplingRate_String>44.1 KHz</SamplingRate_String>
<SamplingCount>601524</SamplingCount>
<FrameCount>587</FrameCount>
<Source_FrameCount>590</Source_FrameCount>
<Compression_Mode>Lossy</Compression_Mode>
<Compression_Mode_String>Lossy</Compression_Mode_String>
<StreamSize>141742</StreamSize>
<StreamSize_String>138 KiB (1%)</StreamSize_String>
<StreamSize_String1>138 KiB</StreamSize_String1>
<StreamSize_String2>138 KiB</StreamSize_String2>
<StreamSize_String3>138 KiB</StreamSize_String3>
<StreamSize_String4>138.4 KiB</StreamSize_String4>
<StreamSize_String5>138 KiB (1%)</StreamSize_String5>
<StreamSize_Proportion>0.00773</StreamSize_Proportion>
<Source_StreamSize>142450</Source_StreamSize>
<Source_StreamSize_String>139 KiB (1%)</Source_StreamSize_String>
<Source_StreamSize_String1>139 KiB</Source_StreamSize_String1>
<Source_StreamSize_String2>139 KiB</Source_StreamSize_String2>
<Source_StreamSize_String3>139 KiB</Source_StreamSize_String3>
<Source_StreamSize_String4>139.1 KiB</Source_StreamSize_String4>
<Source_StreamSize_String5>139 KiB (1%)</Source_StreamSize_String5>
<Source_StreamSize_Proportion>0.00777</Source_StreamSize_Proportion>
<Title>Core Media Audio</Title>
<Encoded_Date>UTC 2015-12-13 02:58:01</Encoded_Date>
<Tagged_Date>UTC 2015-12-13 02:58:15</Tagged_Date>
</track>

<track type="Other" streamid="1">
<Count>65</Count>
<StreamCount>2</StreamCount>
<StreamKind>Other</StreamKind>
<StreamKind_String>Other</StreamKind_String>
<StreamKindID>0</StreamKindID>
<StreamKindPos>1</StreamKindPos>
<Type>meta</Type>
<Duration>13642</Duration>
<Duration_String>13s 642ms</Duration_String>
<Duration_String1>13s 642ms</Duration_String1>
<Duration_String2>13s 642ms</Duration_String2>
<Duration_String3>00:00:13.642</Duration_String3>
<Duration_String5>00:00:13.642</Duration_String5>
<FrameCount>117</FrameCount>
<BitRate_Mode>VBR</BitRate_Mode>
</track>

<track type="Other" streamid="2">
<Count>65</Count>
<StreamCount>2</StreamCount>
<StreamKind>Other</StreamKind>
<StreamKind_String>Other</StreamKind_String>
<StreamKindID>1</StreamKindID>
<StreamKindPos>2</StreamKindPos>
<Type>meta</Type>
<Duration>13642</Duration>
<Duration_String>13s 642ms</Duration_String>
<Duration_String1>13s 642ms</Duration_String1>
<Duration_String2>13s 642ms</Duration_String2>
<Duration_String3>00:00:13.642</Duration_String3>
<Duration_String5>00:00:13.642</Duration_String5>
<FrameCount>1</FrameCount>
<BitRate_Mode>CBR</BitRate_Mode>
</track>

</File>
</Mediainfo>

**Comment by letsgo008** [comment] 2015-12-15 01:00
```XML
<?xml version="1.0" encoding="UTF-8"?>
<Mediainfo version="0.7.74">
<File>
<track type="General">
<Count>313</Count>
<StreamCount>1</StreamCount>
<StreamKind>General</StreamKind>
<StreamKind_String>General</StreamKind_String>
<StreamKindID>0</StreamKindID>
<VideoCount>1</VideoCount>
<AudioCount>1</AudioCount>
<OtherCount>2</OtherCount>
<Video_Format_List>AVC</Video_Format_List>
<Video_Format_WithHint_List>AVC</Video_Format_WithHint_List>
<Video_Codec_List>AVC</Video_Codec_List>
<Audio_Format_List>AAC</Audio_Format_List>
<Audio_Format_WithHint_List>AAC</Audio_Format_WithHint_List>
<Audio_Codec_List>AAC LC</Audio_Codec_List>
<CompleteName>Video-2015-12-13-10-58-01.mp4</CompleteName>
<FileName>Video-2015-12-13-10-58-01</FileName>
<FileExtension>mp4</FileExtension>
<Format>MPEG-4</Format>
<Format_String>MPEG-4</Format_String>
<Format_Extensions>mp4 m4v m4a m4b m4p 3gpp 3gp 3gpp2 3g2 k3g jpm jpx mqv ismv isma f4v</Format_Extensions>
<Format_Commercial>MPEG-4</Format_Commercial>
<Format_Profile>QuickTime</Format_Profile>
<InternetMediaType>video/mp4</InternetMediaType>
<CodecID>qt  </CodecID>
<CodecID_Url>http://www.apple.com/quicktime/download/standalone.html</CodecID_Url>
<Codec>MPEG-4</Codec>
<Codec_String>MPEG-4</Codec_String>
<Codec_Extensions>mp4 m4v m4a m4b m4p 3gpp 3gp 3gpp2 3g2 k3g jpm jpx mqv ismv isma f4v</Codec_Extensions>
<FileSize>18328928</FileSize>
<FileSize_String>17.5 MiB</FileSize_String>
<FileSize_String1>17 MiB</FileSize_String1>
<FileSize_String2>17 MiB</FileSize_String2>
<FileSize_String3>17.5 MiB</FileSize_String3>
<FileSize_String4>17.48 MiB</FileSize_String4>
<Duration>13642</Duration>
<Duration_String>13s 642ms</Duration_String>
<Duration_String1>13s 642ms</Duration_String1>
<Duration_String2>13s 642ms</Duration_String2>
<Duration_String3>00:00:13.642</Duration_String3>
<Duration_String4>00:00:13;19</Duration_String4>
<Duration_String5>00:00:13.642 (00:00:13;19)</Duration_String5>
<OverallBitRate_Mode>VBR</OverallBitRate_Mode>
<OverallBitRate_Mode_String>VBR</OverallBitRate_Mode_String>
<OverallBitRate>10748528</OverallBitRate>
<OverallBitRate_String>10.7 Mbps</OverallBitRate_String>
<FrameRate>29.970</FrameRate>
<FrameRate_String>29.970 fps3</FrameRate_String>
<FrameCount>409</FrameCount>
<StreamSize>33875</StreamSize>
<StreamSize_String>33.1 KiB (0%)</StreamSize_String>
<StreamSize_String1>33 KiB</StreamSize_String1>
<StreamSize_String2>33 KiB</StreamSize_String2>
<StreamSize_String3>33.1 KiB</StreamSize_String3>
<StreamSize_String4>33.08 KiB</StreamSize_String4>
<StreamSize_String5>33.1 KiB (0%)</StreamSize_String5>
<StreamSize_Proportion>0.00185</StreamSize_Proportion>
<HeaderSize>28</HeaderSize>
<DataSize>18319481</DataSize>
<FooterSize>9419</FooterSize>
<IsStreamable>No</IsStreamable>
<Encoded_Date>UTC 2015-12-13 02:58:01</Encoded_Date>
<Tagged_Date>UTC 2015-12-13 02:58:15</Tagged_Date>
<File_Modified_Date>UTC 2015-12-14 08:28:51</File_Modified_Date>
<File_Modified_Date_Local>2015-12-14 16:28:51</File_Modified_Date_Local>
<Encoded_Library>Apple QuickTime</Encoded_Library>
<Encoded_Library_String>Apple QuickTime</Encoded_Library_String>
<Encoded_Library_Name>Apple QuickTime</Encoded_Library_Name>
<comapplequicktimelocationISO6709>+31.2332+121.5340+012.571/</comapplequicktimelocationISO6709>
<comapplequicktimemake>Apple</comapplequicktimemake>
<comapplequicktimemodel>iPhone 6</comapplequicktimemodel>
<comapplequicktimesoftware>9.2</comapplequicktimesoftware>
<comapplequicktimecreationdate>2015-12-13T10:58:01+0800</comapplequicktimecreationdate>
</track>

<track type="Video">
<Count>311</Count>
<StreamCount>1</StreamCount>
<StreamKind>Video</StreamKind>
<StreamKind_String>Video</StreamKind_String>
<StreamKindID>0</StreamKindID>
<StreamOrder>0</StreamOrder>
<ID>1</ID>
<ID_String>1</ID_String>
<Format>AVC</Format>
<Format_Info>Advanced Video Codec</Format_Info>
<Format_Url>http://developers.videolan.org/x264.html</Format_Url>
<Format_Commercial>AVC</Format_Commercial>
<Format_Profile>Baseline@L3.1</Format_Profile>
<Format_Settings>1 Ref Frames</Format_Settings>
<Format_Settings_CABAC>No</Format_Settings_CABAC>
<Format_Settings_CABAC_String>No</Format_Settings_CABAC_String>
<Format_Settings_RefFrames>1</Format_Settings_RefFrames>
<Format_Settings_RefFrames_String>1 frame1</Format_Settings_RefFrames_String>
<Format_Settings_GOP>M=1, N=30</Format_Settings_GOP>
<InternetMediaType>video/H264</InternetMediaType>
<CodecID>avc1</CodecID>
<CodecID_Info>Advanced Video Coding</CodecID_Info>
<CodecID_Url>http://www.apple.com/quicktime/download/standalone.html</CodecID_Url>
<Codec>AVC</Codec>
<Codec_String>AVC</Codec_String>
<Codec_Family>AVC</Codec_Family>
<Codec_Info>Advanced Video Codec</Codec_Info>
<Codec_Url>http://developers.videolan.org/x264.html</Codec_Url>
<Codec_CC>avc1</Codec_CC>
<Codec_Profile>Baseline@L3.1</Codec_Profile>
<Codec_Settings>1 Ref Frames</Codec_Settings>
<Codec_Settings_CABAC>No</Codec_Settings_CABAC>
<Codec_Settings_RefFrames>1</Codec_Settings_RefFrames>
<Duration>13642</Duration>
<Duration_String>13s 642ms</Duration_String>
<Duration_String1>13s 642ms</Duration_String1>
<Duration_String2>13s 642ms</Duration_String2>
<Duration_String3>00:00:13.642</Duration_String3>
<Duration_String4>00:00:13;19</Duration_String4>
<Duration_String5>00:00:13.642 (00:00:13;19)</Duration_String5>
<BitRate>10641657</BitRate>
<BitRate_String>10.6 Mbps</BitRate_String>
<Width>1280</Width>
<Width_String>1280 pixel3</Width_String>
<Height>720</Height>
<Height_String>720 pixel3</Height_String>
<PixelAspectRatio>1.000</PixelAspectRatio>
<DisplayAspectRatio>1.778</DisplayAspectRatio>
<DisplayAspectRatio_String>16:9</DisplayAspectRatio_String>
<Rotation>180.000</Rotation>
<Rotation_String>180°</Rotation_String>
<FrameRate_Mode>VFR</FrameRate_Mode>
<FrameRate_Mode_String>VFR</FrameRate_Mode_String>
<FrameRate>29.970</FrameRate>
<FrameRate_String>29.970 fps3</FrameRate_String>
<FrameRate_Minimum>28.571</FrameRate_Minimum>
<FrameRate_Minimum_String>28.571 fps3</FrameRate_Minimum_String>
<FrameRate_Maximum>30.000</FrameRate_Maximum>
<FrameRate_Maximum_String>30.000 fps3</FrameRate_Maximum_String>
<FrameCount>409</FrameCount>
<Resolution>8</Resolution>
<Resolution_String>8 bit3</Resolution_String>
<Colorimetry>4:2:0</Colorimetry>
<ColorSpace>YUV</ColorSpace>
<ChromaSubsampling>4:2:0</ChromaSubsampling>
<BitDepth>8</BitDepth>
<BitDepth_String>8 bit3</BitDepth_String>
<ScanType>Progressive</ScanType>
<ScanType_String>Progressive</ScanType_String>
<Interlacement>PPF</Interlacement>
<Interlacement_String>Interlaced_PPF</Interlacement_String>
<Bits_Pixel_Frame_>0.385</Bits_Pixel_Frame_>
<StreamSize>18153311</StreamSize>
<StreamSize_String>17.3 MiB (99%)</StreamSize_String>
<StreamSize_String1>17 MiB</StreamSize_String1>
<StreamSize_String2>17 MiB</StreamSize_String2>
<StreamSize_String3>17.3 MiB</StreamSize_String3>
<StreamSize_String4>17.31 MiB</StreamSize_String4>
<StreamSize_String5>17.3 MiB (99%)</StreamSize_String5>
<StreamSize_Proportion>0.99042</StreamSize_Proportion>
<Title>Core Media Video</Title>
<Encoded_Date>UTC 2015-12-13 02:58:01</Encoded_Date>
<Tagged_Date>UTC 2015-12-13 02:58:15</Tagged_Date>
<colour_range>Limited</colour_range>
<colour_description_present>Yes</colour_description_present>
<colour_primaries>BT.709</colour_primaries>
<transfer_characteristics>BT.709</transfer_characteristics>
<matrix_coefficients>BT.709</matrix_coefficients>
</track>

<track type="Audio">
<Count>254</Count>
<StreamCount>1</StreamCount>
<StreamKind>Audio</StreamKind>
<StreamKind_String>Audio</StreamKind_String>
<StreamKindID>0</StreamKindID>
<StreamOrder>1</StreamOrder>
<ID>2</ID>
<ID_String>2</ID_String>
<Format>AAC</Format>
<Format_Info>Advanced Audio Codec</Format_Info>
<Format_Commercial>AAC</Format_Commercial>
<Format_Profile>LC</Format_Profile>
<CodecID>40</CodecID>
<Codec>AAC LC</Codec>
<Codec_String>AAC LC</Codec_String>
<Codec_Family>AAC</Codec_Family>
<Codec_CC>40</Codec_CC>
<Duration>13640</Duration>
<Duration_String>13s 640ms</Duration_String>
<Duration_String1>13s 640ms</Duration_String1>
<Duration_String2>13s 640ms</Duration_String2>
<Duration_String3>00:00:13.640</Duration_String3>
<Duration_String5>00:00:13.640</Duration_String5>
<Source_Duration>13700</Source_Duration>
<Source_Duration_String>13s 700ms</Source_Duration_String>
<Source_Duration_String1>13s 700ms</Source_Duration_String1>
<Source_Duration_String2>13s 700ms</Source_Duration_String2>
<Source_Duration_String3>00:00:13.700</Source_Duration_String3>
<BitRate_Mode>VBR</BitRate_Mode>
<BitRate_Mode_String>VBR</BitRate_Mode_String>
<BitRate>83133</BitRate>
<BitRate_String>83.1 Kbps</BitRate_String>
<Channel_s_>1</Channel_s_>
<Channel_s__String>1 channel1</Channel_s__String>
<ChannelPositions>Front: C</ChannelPositions>
<ChannelPositions_String2>1/0/0</ChannelPositions_String2>
<ChannelLayout>C</ChannelLayout>
<SamplingRate>44100</SamplingRate>
<SamplingRate_String>44.1 KHz</SamplingRate_String>
<SamplingCount>601524</SamplingCount>
<FrameCount>587</FrameCount>
<Source_FrameCount>590</Source_FrameCount>
<Compression_Mode>Lossy</Compression_Mode>
<Compression_Mode_String>Lossy</Compression_Mode_String>
<StreamSize>141742</StreamSize>
<StreamSize_String>138 KiB (1%)</StreamSize_String>
<StreamSize_String1>138 KiB</StreamSize_String1>
<StreamSize_String2>138 KiB</StreamSize_String2>
<StreamSize_String3>138 KiB</StreamSize_String3>
<StreamSize_String4>138.4 KiB</StreamSize_String4>
<StreamSize_String5>138 KiB (1%)</StreamSize_String5>
<StreamSize_Proportion>0.00773</StreamSize_Proportion>
<Source_StreamSize>142450</Source_StreamSize>
<Source_StreamSize_String>139 KiB (1%)</Source_StreamSize_String>
<Source_StreamSize_String1>139 KiB</Source_StreamSize_String1>
<Source_StreamSize_String2>139 KiB</Source_StreamSize_String2>
<Source_StreamSize_String3>139 KiB</Source_StreamSize_String3>
<Source_StreamSize_String4>139.1 KiB</Source_StreamSize_String4>
<Source_StreamSize_String5>139 KiB (1%)</Source_StreamSize_String5>
<Source_StreamSize_Proportion>0.00777</Source_StreamSize_Proportion>
<Title>Core Media Audio</Title>
<Encoded_Date>UTC 2015-12-13 02:58:01</Encoded_Date>
<Tagged_Date>UTC 2015-12-13 02:58:15</Tagged_Date>
</track>

<track type="Other" streamid="1">
<Count>65</Count>
<StreamCount>2</StreamCount>
<StreamKind>Other</StreamKind>
<StreamKind_String>Other</StreamKind_String>
<StreamKindID>0</StreamKindID>
<StreamKindPos>1</StreamKindPos>
<Type>meta</Type>
<Duration>13642</Duration>
<Duration_String>13s 642ms</Duration_String>
<Duration_String1>13s 642ms</Duration_String1>
<Duration_String2>13s 642ms</Duration_String2>
<Duration_String3>00:00:13.642</Duration_String3>
<Duration_String5>00:00:13.642</Duration_String5>
<FrameCount>117</FrameCount>
<BitRate_Mode>VBR</BitRate_Mode>
</track>

<track type="Other" streamid="2">
<Count>65</Count>
<StreamCount>2</StreamCount>
<StreamKind>Other</StreamKind>
<StreamKind_String>Other</StreamKind_String>
<StreamKindID>1</StreamKindID>
<StreamKindPos>2</StreamKindPos>
<Type>meta</Type>
<Duration>13642</Duration>
<Duration_String>13s 642ms</Duration_String>
<Duration_String1>13s 642ms</Duration_String1>
<Duration_String2>13s 642ms</Duration_String2>
<Duration_String3>00:00:13.642</Duration_String3>
<Duration_String5>00:00:13.642</Duration_String5>
<FrameCount>1</FrameCount>
<BitRate_Mode>CBR</BitRate_Mode>
</track>

</File>
</Mediainfo>
```

**Comment by letsgo008** [comment] 2015-12-15 01:18
$exif['model'] .= " ". (string)$general->comapplequicktimesoftware;
this line error

```XML
if (isset($general->xyz))
{
    //$test = "+35.6445-139.7455-029.201/";
    //print_r(preg_split('/(\+|\-)/', $general->xyz, -1, PREG_SPLIT_DELIM_CAPTURE));
    $value = preg_split('/(\+|\-)/', $general->xyz, -1, PREG_SPLIT_DELIM_CAPTURE);
    $exif['latitude'] = $value[1].$value[2];
    $exif['longitude'] = $value[3].$value[4];
}
```
I don't find "xyz" information

**Comment by xbgmsharp** [comment] 2015-12-15 14:59
If there is no "xyz" information, you won't get into the ``if``.

```PHP
$exif['model'] .= " ". (string)$general->comapplequicktimesoftware;
```
Should match 
```XML
<comapplequicktimesoftware>9.2</comapplequicktimesoftware>
```
https://github.com/xbgmsharp/piwigo-videojs/blob/master/include/mediainfo.php#L126

**Comment by xbgmsharp** [comment] 2015-12-15 17:01
I think the issue is because ``$exif['model']`` is not define as ``$general->Model`` does not exist.
https://github.com/xbgmsharp/piwigo-videojs/blob/master/include/mediainfo.php#L122
The idea would to change L122 from:
```
if (isset($general->Model))
```
to
```
if (isset($general->Model) or isset($general->comapplequicktimemodel))
```

The same would help on L130 from:
https://github.com/xbgmsharp/piwigo-videojs/blob/master/include/mediainfo.php#L130
```
if (isset($general->Make))
```
to
```
if (isset($general->Make) or isset($general->comapplequicktimemake))
```

In regards to the XZY, the same L114 from:
https://github.com/xbgmsharp/piwigo-videojs/blob/master/include/mediainfo.php#L114
```
if (isset($general->xyz))
```
to
```
if (isset($general->xyz)) or isset($general->comapplequicktimelocationISO6709))
```

I will submit a patch.

**Comment by xbgmsharp** [comment] 2015-12-15 17:16
Please update the file to this latest version and feedback.
https://raw.githubusercontent.com/xbgmsharp/piwigo-videojs/b6e71eb05a1fe2e6833ba4fe454ec21d1ce1b066/include/mediainfo.php
Make sure to test with new and old video.

**Comment by xbgmsharp** [comment] 2016-06-05 09:46
Closing the issue, publish on new release v2.8.a

**Closed by xbgmsharp** 2016-06-05 09:46 UTC
