### ISSUE TITLE
Posters broken if piwigo is installed in a subdirectory

### ISSUE THREAD

**Issue by sillybuggers** [xbgmsharp/piwigo-videojs#26] opened 2014-07-26 17:48 UTC
Poster URL is incorrect if piwigo is installed in subdirectory of the domain. Here is the generated HTML code for the poster if piwigo is located in www.example.com/piwigo:

          </div><div class="vjs-poster" tabindex="-1" style="background-image: url(http://www.example.com/piwigo//piwigo/galleries/Videos/pwg_representative/DSCN1015.jpg);"></div>

while it should have been

          </div><div class="vjs-poster" tabindex="-1" style="background-image: url(http://www.example.com/piwigo/galleries/Videos/pwg_representative/DSCN1015.jpg);"></div>

**Comment by xbgmsharp** [comment] 2015-02-20 14:15
I try the following scenario:
 * Subalbum of album and no issue
 * Virtual subalbum of album and no issue

I am unable to reproduce the issue.
Could you please test and feedback using the latest github version with PWG2.7?

**Comment by leonkiriliuk** [comment] 2015-02-20 14:51
The issue was repaired in PWG2.7 ..

**Comment by xbgmsharp** [comment] 2015-02-20 14:57
Great news, thanks for the help and support.
Closing.

**Closed by xbgmsharp** 2015-02-20 14:57 UTC
