### ISSUE TITLE
How to install with these two files required?  MediaInfo and FFmpeg

### ISSUE THREAD

**Issue by ghost** [xbgmsharp/piwigo-videojs#35] opened 2014-10-08 23:37 UTC
I am confused.  I am not currently a programmer, but familiar with information of where to put programs to make the main programs work.  I have piwigo installed on my host machine with Globat which I believe uses the linux system. Works GREAT!  I wanted to have videos work and found this newly updated VIDEOJS plugin and installed and activated. Then was informed need MediaInfo and FFmpeg. I downloaded these two files and ready to install and activate. But how to install and where? I tried to find instructions how and where to install them and no luck.  I am using piwigo version 2.7.0. 

I need step by step instructions how and where to install MediaInfo and FFmpeg. 

Looking forward to any answers to this request.

Thanks,
Gary
gkroush (at) gmail.com 

PS If need to see it, it is www.gkroush.com/piwigo/     I have only one video uploaded and will upload more when I am able to successfully see the video working when clicked on to play.

**Comment by xbgmsharp** [comment] 2015-02-20 14:12
Do you need any more assistance or is everything fine for you?

**Comment by gkroush** [comment] 2015-02-20 16:59
I got confused on how /where to install exactly. I am not a developer. Just
a main person for my family to running/maintaining the piwigo program
installed in the system.

Do I install those external programs on my PC, or install on the Web host
server in the directory where piwigo is installed? I use Globat shared web
hosting which it uses Linux system.

Which video type file is best to run?

Thanks for checking.

Gary

**Comment by xbgmsharp** [comment] 2015-02-21 12:01
Here is the [supported HTML5 video](http://www.videojs.com/html5-video-support/). H.264 is the most famous format.
You need install those tools on the Web host server where piwigo is installed.
You can ask your hosting company to have those binary install on the Web host server system.

You don't necessary need those external tools to play the video as those software are use to generate the thumbnail and poster as well as metadata parsing.

I updated the wiki with your feedback.
https://github.com/xbgmsharp/piwigo-videojs/wiki/Synchronize#requirement
https://github.com/xbgmsharp/piwigo-videojs/wiki#external-tools

**Comment by joselette** [comment] 2016-05-27 15:21
Hi, just trying to setup in a IIS server:

```
Mediainfo error reading file
Is MediaInfo install?
Is MediaInfo in path?
Is the video accessible & readable
Try to run the command manually.
--Full --Output=XML --Language=raw './galleries/2016/01_Enero/01_Cabalgata_Reyes/2016-01-05_Lanzarotte_0003.mp4'
```
not sure paths are setup correctly:
path: C:\Archivos de programa (portable)\tools\

Also including that path in path system var seems not to work.

**Comment by xbgmsharp** [comment] 2016-05-30 09:25
You need to donwload an install those external tools. 
https://github.com/xbgmsharp/piwigo-videojs/wiki/How-to-add-videos#external-tools
For MediaInfo only the CLI is needed, https://mediaarea.net/en/MediaInfo/Download/Windows
For https://libav.org/download/
Your webserver need to be able to access the directory, in your case ``path: C:\Archivos de programa (portable)\tools\``
If MediaInfo and FFmpeg are not in the environment path. You must set the full path (to the exe files and quote for windows) in program dependencies, eg : ``"C:\Archivos de programa (portable)\tools\MediaInfo\MediaInfo.exe"``
You must have the PHP ``system()`` and ``shell_exec()`` call enable.

**Comment by xbgmsharp** [comment] 2016-05-30 10:28
There is apparently a bug on Windows Please check issue #84

**Comment by digibirdtrek** [comment] 2016-06-11 12:51
Ability to disable exif display for videos only when these plugins are not available.  Playing video will work when exif display is disabled via config, but that also disables photo exif display.

**Comment by xbgmsharp** [comment] 2016-06-12 08:01
This is a different request. However, not sure I fully understand metadata are only display on request. Also If you don't add any Video specify in the metadata config array, you wont see them.
https://github.com/xbgmsharp/piwigo-videojs/wiki/How-to-add-videos#add-video-metadata-support
Please create a new issue and provide more details.

**Comment by xbgmsharp** [comment] 2018-07-26 08:43
@digibirdtrek there is an option to disable metadata parsing. There is no more hard reference to MediaInfo.
I am unable to reproduce the issue, so closing. 
From version 2.9.a only ffmpeg is require to generate thumbnails and metadata.

**Closed by xbgmsharp** 2018-07-26 08:43 UTC
Labels: question

**Comment by odtmusisi19** [comment] 2024-01-13 01:50
how to use ffmpeg plugin on media info apliccation for windows 11?
